# Generated by Django 5.1.7 on 2026-08-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_systemsetting_organization_and_more'),
        ('templates_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='common.organization'),
        ),
    ]
