# Generated by Django 5.1.7 on 2026-08-18 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_organization_max_admins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('price_bdt', models.PositiveIntegerField()),
                ('email_limit', models.PositiveIntegerField()),
                ('daily_email_limit', models.PositiveIntegerField(default=0)),
                ('weekly_email_limit', models.PositiveIntegerField(default=0)),
                ('max_admins', models.PositiveIntegerField()),
                ('max_users', models.PositiveIntegerField()),
                ('max_smtp_accounts', models.PositiveIntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'price_bdt'),
            },
        ),
        migrations.CreateModel(
            name='FreePlanClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, unique=True)),
                ('email_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_plan_claim', to='common.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='common.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('organization_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('network', models.CharField(choices=[('bsc', 'BNB Smart Chain'), ('ethereum', 'Ethereum'), ('tron', 'Tron'), ('ton', 'TON')], max_length=16)),
                ('receiving_address', models.CharField(max_length=128)),
                ('token_contract', models.CharField(max_length=128)),
                ('price_bdt', models.PositiveIntegerField()),
                ('usdt_bdt_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verifying', 'Verifying'), ('paid', 'Paid'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('transaction_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('transfer_index', models.PositiveIntegerField(default=0)),
                ('verification_error', models.TextField(blank=True)),
                ('verification_data', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoices', to='common.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.plan')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('transaction_hash__isnull', False)), fields=('network', 'transaction_hash', 'transfer_index'), name='unique_consumed_chain_transfer')],
            },
        ),
    ]
