# Generated by Codex on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_seed_subscription_plans"),
    ]

    operations = [
        migrations.AddField("paymentinvoice", "access_token_digest", models.CharField(blank=True, db_index=True, max_length=64)),
        migrations.AddField("paymentinvoice", "encrypted_access_token", models.TextField(blank=True)),
        migrations.AddField("paymentinvoice", "access_token_created_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "access_token_last_used_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "idempotency_key", models.CharField(blank=True, db_index=True, max_length=96)),
        migrations.AddField(
            "paymentinvoice",
            "replaced_by",
            models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replaces", to="billing.paymentinvoice"),
        ),
        migrations.AddField("paymentinvoice", "cancelled_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "replaced_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "invoice_email_sent_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "invoice_email_error", models.TextField(blank=True)),
        migrations.AddField("paymentinvoice", "recovery_email_sent_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "recovery_email_error", models.TextField(blank=True)),
        migrations.AddField("paymentinvoice", "confirmation_email_sent_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "confirmation_email_error", models.TextField(blank=True)),
        migrations.AddField("paymentinvoice", "manual_review_email_sent_at", models.DateTimeField(blank=True, null=True)),
        migrations.AddField("paymentinvoice", "manual_review_email_error", models.TextField(blank=True)),
        migrations.AlterField(
            "paymentinvoice",
            "status",
            models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verifying", "Verifying"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("replaced", "Replaced"),
                    ("manual_review", "Manual review"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
