# Generated by Django 5.1.7 on 2026-08-18 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def backfill_invoice_security_fields(apps, schema_editor):
    PaymentInvoice = apps.get_model("billing", "PaymentInvoice")
    decimals_by_network = {"bsc": 18, "ethereum": 6, "tron": 6, "ton": 6}
    for invoice in PaymentInvoice.objects.select_related("plan").all():
        decimals = decimals_by_network.get(invoice.network, 6)
        invoice.normalized_customer_email = (invoice.customer_email or "").strip().lower()
        invoice.normalized_organization_name = " ".join((invoice.organization_name or "").strip().lower().split())
        invoice.token_decimals = decimals
        invoice.amount_raw = (Decimal(invoice.amount_usdt or 0) * (Decimal(10) ** decimals)).quantize(Decimal("1"))
        if invoice.plan_id and not invoice.snapshot_limits:
            plan = invoice.plan
            invoice.snapshot_limits = {
                "email_limit": plan.email_limit,
                "daily_email_limit": plan.daily_email_limit,
                "weekly_email_limit": plan.weekly_email_limit,
                "max_admins": plan.max_admins,
                "max_users": plan.max_users,
                "max_smtp_accounts": plan.max_smtp_accounts,
                "max_recipients": plan.max_recipients,
                "max_campaigns_per_day": plan.max_campaigns_per_day,
            }
        invoice.save(update_fields=(
            "normalized_customer_email", "normalized_organization_name", "token_decimals",
            "amount_raw", "snapshot_limits",
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_organization_limits'),
        ('common', '0006_billingconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentSecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransferLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('bsc', 'BNB Smart Chain'), ('ethereum', 'Ethereum'), ('tron', 'Tron'), ('ton', 'TON')], max_length=16)),
                ('transaction_hash', models.CharField(max_length=128)),
                ('transfer_index', models.PositiveIntegerField(default=0)),
                ('canonical_contract', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('amount_raw', models.DecimalField(decimal_places=0, max_digits=48)),
                ('amount_usdt', models.DecimalField(decimal_places=6, max_digits=20)),
                ('block_reference', models.CharField(blank=True, max_length=128)),
                ('confirmations', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('provider_proofs', models.JSONField(blank=True, default=dict)),
                ('resolution', models.CharField(choices=[('unresolved', 'Unresolved'), ('auto_activated', 'Auto activated'), ('manual_approved', 'Manual approved'), ('manual_rejected', 'Manual rejected'), ('manual_refunded', 'Manual refunded')], default='unresolved', max_length=24)),
                ('resolution_history', models.JSONField(blank=True, default=list)),
                ('refund_transaction_hash', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='amount_raw',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=48),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='normalized_customer_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='normalized_organization_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='snapshot_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='token_decimals',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.RunPython(backfill_invoice_security_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'verifying'))), fields=('normalized_customer_email',), name='unique_active_invoice_per_normalized_email'),
        ),
        migrations.AddConstraint(
            model_name='paymentinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('normalized_customer_email', 'idempotency_key'), name='unique_checkout_idempotency_per_email'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='billing.paymentinvoice'),
        ),
        migrations.AddField(
            model_name='paymentsecurityauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsecurityauditevent',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.paymentinvoice'),
        ),
        migrations.AddField(
            model_name='paymenttransferledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_ledgers', to='billing.paymentinvoice'),
        ),
        migrations.AddField(
            model_name='paymentsecurityauditevent',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='billing.paymenttransferledger'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransferledger',
            constraint=models.UniqueConstraint(fields=('network', 'transaction_hash', 'transfer_index'), name='unique_transfer_ledger_entry'),
        ),
    ]
