# Generated by Codex on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def revoke_legacy_invoice_access(apps, schema_editor):
    PaymentInvoice = apps.get_model("billing", "PaymentInvoice")
    CheckoutSession = apps.get_model("billing", "CheckoutSession")
    PaymentInvoice.objects.exclude(access_token_digest="").update(
        access_token_digest="",
        encrypted_access_token="",
        access_token_created_at=None,
    )
    CheckoutSession.objects.filter(revoked_at__isnull=True).update(revoked_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_checkoutemailverification_precheckoutsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAccessCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_digest", models.CharField(db_index=True, max_length=64, unique=True)),
                ("encrypted_delivery_copy", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="access_codes", to="billing.paymentinvoice")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.RunPython(revoke_legacy_invoice_access, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="paymenttransferledger",
            name="occurred_at",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
