# Generated by Codex on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_invoiceaccesscode_require_ledger_occurred_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("pending", "verifying"))),
                fields=("normalized_organization_name",),
                name="unique_active_invoice_per_normalized_org",
            ),
        ),
    ]
