# Generated by Django 5.1.7 on 2026-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.TextField()),
                ('encryption', models.CharField(choices=[('none', 'None'), ('tls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='tls', max_length=10)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('daily_limit', models.PositiveIntegerField(default=1000)),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
