# Generated by Django 5.1.7 on 2026-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
