# Generated by Django 5.1.7 on 2026-08-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_systemsetting_organization_and_more'),
        ('smtp_manager', '0002_smtpaccount_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_accounts', to='common.organization'),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
