# Generated by Django 5.1.7 on 2026-08-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('recipients', '0001_initial'),
        ('smtp_manager', '0001_initial'),
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recipient_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='recipients.recipientlist'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='smtp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='smtp_manager.smtpaccount'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='templates_app.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaignlog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignlog',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_logs', to='recipients.recipient'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_47a27a_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignlog',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient_email'), name='unique_campaign_recipient_email'),
        ),
    ]
