# Generated by Django 5.1.7 on 2026-08-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('templates_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='templates_app.emailtemplate'),
        ),
    ]
