# Generated by Django 5.1.7 on 2026-08-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_template'),
        ('smtp_manager', '0002_smtpaccount_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='smtp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='smtp_manager.smtpaccount'),
        ),
    ]
