# Generated by Django 5.1.7 on 2026-08-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_smtp'),
        ('recipients', '0003_recipient_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='recipient_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='recipients.recipientlist'),
        ),
    ]
