# Generated by Django 5.1.7 on 2026-08-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_recipient_list'),
        ('common', '0002_organization_systemsetting_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='common.organization'),
        ),
        migrations.AddField(
            model_name='campaignlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to='common.organization'),
        ),
    ]
