# Generated by Django 5.1.7 on 2026-08-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Mail Automation Engine', max_length=255)),
                ('company_name', models.CharField(default='Acme Enterprises Inc.', max_length=255)),
                ('default_sender_name', models.CharField(default='Marketing Team', max_length=255)),
                ('default_sender_email', models.EmailField(default='marketing@acme.com', max_length=254)),
                ('default_reply_to', models.EmailField(default='support@acme.com', max_length=254)),
                ('default_timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('default_page_size', models.PositiveIntegerField(default=10)),
                ('default_smtp', models.CharField(blank=True, default='', max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=300)),
                ('batch_size', models.PositiveIntegerField(default=50)),
                ('delay_between_emails', models.PositiveIntegerField(default=1)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('open_tracking', models.BooleanField(default=True)),
                ('click_tracking', models.BooleanField(default=True)),
                ('plaintext_fallback', models.BooleanField(default=True)),
                ('unsubscribe_footer', models.TextField(default='You are receiving this email because you opted into our newsletter. Click here to unsubscribe.')),
                ('max_upload_size_mb', models.PositiveIntegerField(default=25)),
                ('allowed_image_formats', models.CharField(default='jpg, png, gif, webp', max_length=255)),
                ('allowed_attachment_formats', models.CharField(default='pdf, docx, xlsx, zip', max_length=255)),
                ('media_storage_path', models.CharField(default='/var/mail_automation/media/', max_length=255)),
                ('file_retention_days', models.PositiveIntegerField(default=90)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('login_attempt_limit', models.PositiveIntegerField(default=5)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=365)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
