# Generated by Django 5.1.7 on 2026-08-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_backfill_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_admins',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='weekly_email_limit',
            field=models.PositiveIntegerField(default=0, help_text='Zero means no weekly limit.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='daily_email_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Zero means no daily limit.'),
        ),
    ]
