# Generated by Django 5.1.7 on 2026-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_organization_alter_user_role_userloginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
