# Generated by Django 5.1.7 on 2026-08-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientlist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='recipient_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='recipients.recipientlist'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['email'], name='recipients__email_bd697a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['status'], name='recipients__status_74bd82_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('recipient_list', 'email'), name='unique_recipient_per_list'),
        ),
    ]
