# Generated by Django 5.1.7 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
