# Generated by Django 5.1.7 on 2026-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipient_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
