# Generated by Django 5.1.7 on 2026-08-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_organization_systemsetting_organization_and_more'),
        ('recipients', '0004_recipient_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='common.organization'),
        ),
        migrations.AddField(
            model_name='recipientlist',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_lists', to='common.organization'),
        ),
    ]
